name: E2E OpenCL

on:
  workflow_call:

permissions:
  contents: read
  pull-requests: write

jobs:
  e2e-build-hw:
    if: github.repository == 'oneapi-src/unified-runtime'  # run only on upstream; forks will not have the HW
    name: Start e2e job
    # use core flow, run it with OpenCL specific parameters
    uses: ./.github/workflows/e2e_core.yml
    with:
      name: "OPENCL"
      runner_tag: "OPENCL"
      str_name: "opencl"
      prefix: ""
      config: ""
      unit: "cpu"
      xfail: "AOT/double.cpp;AOT/half.cpp;AOT/reqd-sg-size.cpp;Basic/built-ins/marray_geometric.cpp;KernelCompiler/kernel_compiler_spirv.cpp;KernelCompiler/opencl_queries.cpp"
      extra_lit_flags: "-sv --max-time=3600"
