name: SYCL E2E on Nightly build

on:
  workflow_call:
    inputs:
      name:
        type: string
      runner:
        type: string
      image:
        type: string
      extra_cmake_args:
        type: string
      extra_image_opts:
        type: string
      target_devices:
        type: string
      ref:
        type: string

jobs:
  lin_e2e_only:
    name: ${{ inputs.name }}
    runs-on: ${{ fromJSON(inputs.runner) }}
    container:
      image: ${{ inputs.image }}
      options: --device=/dev/dri --privileged --cap-add SYS_ADMIN ${{ inputs.extra_image_opts }}
    steps:
    - uses: actions/checkout@v3
      with:
        path: llvm
        ref: ${{ inputs.ref }}
        sparse-checkout: |
          devops/actions
          sycl/test-e2e
          llvm/utils
    - name: Register cleanup after job is finished
      uses: ./llvm/devops/actions/cleanup
    - name: Configure
      run: |
        cmake -GNinja -B./build-e2e -S./llvm/sycl/test-e2e -DSYCL_TEST_E2E_TARGETS="${{ inputs.target_devices }}" -DCMAKE_CXX_COMPILER="clang++" -DLLVM_LIT="$PWD/llvm/llvm/utils/lit/lit.py" ${{ inputs.extra_cmake_args }}
    # opencl:cpu backend won't be visible in the sycl-ls commands below, see the
    # comment below referencing https://github.com/actions/runner/issues/1964.
    - run: sycl-ls --verbose
    - run: SYCL_PI_TRACE=-1 sycl-ls
    - name: SYCL End-to-end tests
      env:
        LIT_OPTS: -v --no-progress-bar --show-unsupported --max-time 3600 --time-tests
      shell: bash
      run: |
        # https://github.com/actions/runner/issues/1964 prevents us from using
        # the ENTRYPOINT in the image.
        if [ -e /runtimes/oneapi-tbb/env/vars.sh ]; then
          source /runtimes/oneapi-tbb/env/vars.sh;
        elif [ -e /opt/runtimes/oneapi-tbb/env/vars.sh ]; then
          source /opt/runtimes/oneapi-tbb/env/vars.sh;
        else
          echo "no TBB vars in /opt/runtimes or /runtimes";
        fi
        ninja -C build-e2e check-sycl-e2e
