name: Update GPU driver

on:
  schedule:
    - cron:  '0 3 * * 2'
  workflow_dispatch:

jobs:
  update_driver_linux:
    runs-on: ubuntu-20.04
    if: github.repository == 'intel/llvm'
    steps:
    - uses: actions/checkout@v4
    - name: Update dependencies file
      run: |
        version="$(python3 devops/scripts/update_drivers.py linux)"
        echo 'NEW_DRIVER_VERSION='$version >> $GITHUB_ENV
    - name: Create Pull Request
      env:
        BRANCH: ci/update_gpu_driver-linux-${{ env.NEW_DRIVER_VERSION }}
        GITHUB_TOKEN: ${{ secrets.LLVM_MAIN_SYNC_BBSYCL_TOKEN }}
      run: |
        cd $GITHUB_WORKSPACE
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git checkout -B $BRANCH
        git add -u
        git commit -m "[GHA] Uplift Linux GPU RT version to $NEW_DRIVER_VERSION" || exit 0   # exit if commit is empty
        git push https://$GITHUB_TOKEN@github.com/${{ github.repository }} ${BRANCH}
        gh pr create --head $BRANCH --title "[GHA] Uplift Linux GPU RT version to $NEW_DRIVER_VERSION" --body "Scheduled drivers uplift"
