name: Reusable test matrix generation

on:
  workflow_call:
    inputs:
      intel_drivers_image:
        type: string
        required: false
        default: "ghcr.io/intel/llvm/ubuntu2004_intel_drivers:latest"
      amdgpu_image:
        type: string
        required: false
        default: "ghcr.io/intel/llvm/ubuntu2004_build:latest"
      cuda_image:
        type: string
        required: false
        default: "ghcr.io/intel/llvm/ubuntu2004_build:latest"
      lts_config:
        type: string
        required: true
        default: ""
      uniq:
        description: Unique string to name dynamic runners in AWS
        type: string
        required: false
        default: ${{ github.run_id }}-${{ github.run_attempt }}
      ref:
        description: "Commit to use for checkout or github.sha by default"
        type: string
        required: false
    outputs:
      lts_matrix:
        description: "Generated Matrix"
        value: ${{ jobs.test_matrix.outputs.lts_matrix }}
      lts_aws_matrix:
        description: "Generated Matrix AWS subset"
        value: ${{ jobs.test_matrix.outputs.lts_aws_matrix }}
jobs:
  test_matrix:
    name: Generate Test Matrix
    runs-on: ubuntu-latest
    outputs:
      lts_matrix: ${{ steps.work.outputs.lts_matrix }}
      lts_aws_matrix: ${{ steps.work.outputs.lts_aws_matrix }}
    steps:
    - name: Download scripts and configs
      shell: bash
      run: |
        wget raw.githubusercontent.com/intel/llvm/${{ inputs.ref || github.sha }}/devops/scripts/generate_test_matrix.js
        wget raw.githubusercontent.com/intel/llvm/${{ inputs.ref || github.sha }}/devops/test_configs.json
        wget raw.githubusercontent.com/intel/llvm/sycl/devops/dependencies.json
        mv dependencies.json dependencies.sycl.json
        wget raw.githubusercontent.com/intel/llvm/${{ inputs.ref || github.sha }}/devops/dependencies.json
    - id: work
      uses: actions/github-script@v6
      name: Generate matrix
      env:
        GHA_INPUTS: ${{ toJSON(inputs) }}
      with:
        script: |
          const script = require('./generate_test_matrix.js');
          script({core, process});
