name: Update GPU driver

on:
  schedule:
    - cron:  '0 3 * * 2'
  workflow_dispatch:

jobs:
  update_driver_linux:
    runs-on: ubuntu-latest
    #if: github.repository == 'intel/llvm'
    steps:
    - uses: actions/checkout@v2
    - name: Update dependencies file
      run: |
        version="$(python3 devops/scripts/update_drivers.py linux)"
        echo 'NEW_DRIVER_VERSION='$version >> $GITHUB_ENV
    - name: Create Pull Request
      env:
        BRANCH: ci/update_gpu_driver
        LLVMBOT_TOKEN: ${{ secrets.LLVM_MAIN_SYNC_BBSYCL_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd $GITHUB_WORKSPACE/src
        git checkout -B $BRANCH
        git add -u
        git commit -m "[GHA] Uplift GPU RT version for Linux CI"
        git push https://$LLVMBOT_TOKEN@github.com/${{ github.repository }} ${BRANCH}
        gh pr create --title "[GHA] Uplift GPU RT version for Linux CI" --body "Uplift GPU RT version for Linux to $NEW_DRIVER_VERSION" --assignee @intel/dpcpp-devops-reviewers

  update_driver_linux_staging:
    runs-on: ubuntu-latest
    #if: github.repository == 'intel/llvm'
    steps:
    - uses: actions/checkout@v2
    - name: Update dependencies file
      run: |
        version="$(devops/scripts/update_drivers.py linux_staging)"
        echo 'NEW_DRIVER_VERSION='$version >> $GITHUB_ENV
    - name: Create Pull Request
      env:
        BRANCH: ci/update_gpu_driver
        LLVMBOT_TOKEN: ${{ secrets.LLVM_MAIN_SYNC_BBSYCL_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd $GITHUB_WORKSPACE/src
        git checkout -B $BRANCH
        git add -u
        git commit -m "[GHA] Uplift GPU RT version for Nightly runs"
        git push https://$LLVMBOT_TOKEN@github.com/${{ github.repository }} ${BRANCH}
        gh pr create --title "[GHA] Uplift GPU RT version for Nightly runs" --body "Uplift GPU RT version for Linux Staging to $NEW_DRIVER_VERSION" --assignee @intel/dpcpp-devops-reviewers

